export interface Product {
    id: number,
    id_enterprise: number,
    image: string,
    name: string,
    description: string,
    category: number,
    category_item: string,
    category_color: string,
    filters: string,
    filter_values: string[],
    sku: string,
    stock_real: number,
    stock_available: number,
    storage_location: number,
    storage_name: string,
    sale_price: GLfloat,
    purchase_price: GLfloat,
    provider: number,
    provider_name: string,
    purchase_date: string,
    sale_date: string,
    state: string
}

export const empty_product: Product = {
    id: 0,
    id_enterprise: 0,
    image: '',
    name: '',
    description: '',
    category: 0,
    category_item: '',
    category_color: '',
    filters: '',
    filter_values: [''],
    sku: '',
    stock_real: 0,
    stock_available: 0,
    storage_location: 0,
    storage_name: '',
    sale_price: 0.00,
    purchase_price: 0.00,
    provider: 0,
    provider_name: '',
    purchase_date: '',
    sale_date: '',
    state: 'inactivo'
}