export interface Product {
    id: number,
    id_enterprise: number,
    image: string,
    name: string,
    description: string,
    category: number,
    category_item: string,
    category_color: string,
    id_option_1: number,
    id_option_2: number,
    sku: string,
    stock_real: number,
    is_stock: string,
    stock_available: number,
    storage_location: number,
    storage_name: string,
    sale_price: GLfloat,
    purchase_price: GLfloat,
    provider: number,
    provider_name: string,
    purchase_date: string,
    sale_date: string,
    state: string
}